name: Runing tests


on:
  workflow_dispatch:
  push:
    branch: "master"

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: |
          pnpm install

        env:
          PUBLIC_PB_URL: ${{ vars.PUBLIC_PB_URL }}
      
      - name: Testing

        env:
          PUBLIC_PB_URL: ${{ vars.PUBLIC_PB_URL }}
        
        run: |
          pnpm run test